hyperskill_project:
  id: 91
  ide_files: https://stepik.org/media/attachments/lesson/287312/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Mon, 18 Jan 2021 11:48:11 UTC
stages:
- id: 504
  step: 8252
  is_completed: true
- id: 505
  step: 8253
  is_completed: true
- id: 506
  step: 8254
  is_completed: true
- id: 507
  step: 8255
  is_completed: true
- id: 508
  step: 8256
  is_completed: true
- id: 509
  step: 8257
  is_completed: true
topics:
  0:
  - title: External resources
    theory_id: 6216
  - title: Units of information
    theory_id: 6865
  - title: Introduction to OOP
    theory_id: 3614
  - title: Frameworks
    theory_id: 6701
  - title: Immutability
    theory_id: 7929
  - title: Computer algorithms
    theory_id: 4953
  - title: Introducing the first algorithm
    theory_id: 10336
  - title: The big O notation
    theory_id: 4991
  - title: Data structures
    theory_id: 5161
  - title: Fixed-size array
    theory_id: 7255
  - title: Dynamic array
    theory_id: 5357
  - title: World Wide Web
    theory_id: 6633
  - title: HyperText Transfer Protocol
    theory_id: 6569
  - title: HTTP URL
    theory_id: 6740
  - title: HTTP messages
    theory_id: 6752
  - title: REST
    theory_id: 7834
  - title: JSON
    theory_id: 6854
  - title: Postman
    theory_id: 8512
  - title: IDE
    theory_id: 10996
  - title: Introduction to Spring Boot
    theory_id: 7944
  - title: Write, compile, and run
    theory_id: 3739
  - title: JVM, JRE, and JDK
    theory_id: 3499
  - title: What is an exception
    theory_id: 3497
  - title: NPE
    theory_id: 1945
  - title: Generic programming
    theory_id: 3492
  - title: What are collections
    theory_id: 3770
  - title: ArrayList
    theory_id: 3567
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Getting started with Spring Boot
    theory_id: 6336
  - title: Basic project structure
    theory_id: 6339
  - title: Rest controller
    theory_id: 7015
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Comments
    theory_id: 3520
  - title: Naming variables
    theory_id: 3513
  - title: Scanning the input
    theory_id: 9055
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Increment and decrement
    theory_id: 5008
  - title: Characters
    theory_id: 3514
  - title: Conditional statement
    theory_id: 3503
  - title: Ternary operator
    theory_id: 3506
  - title: The for-loop
    theory_id: 3505
  - title: The while and do-while loops
    theory_id: 3498
  - title: Branching statements
    theory_id: 3507
  - title: Switch statement
    theory_id: 3504
  - title: Calling a method
    theory_id: 10973
  - title: Declaring a method
    theory_id: 10982
  - title: The main method
    theory_id: 3489
  - title: Overloading
    theory_id: 3525
  - title: Functional decomposition
    theory_id: 10570
  - title: Primitive and reference types
    theory_id: 5035
  - title: Array
    theory_id: 3511
  - title: Iterating over arrays
    theory_id: 3602
  - title: String
    theory_id: 3523
  - title: Final variables
    theory_id: 7427
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: Errors in programs
    theory_id: 3536
  - title: Defining classes
    theory_id: 3618
  - title: Package
    theory_id: 3621
  - title: Constructor
    theory_id: 3535
  - title: Objects
    theory_id: 4727
  - title: Instance methods
    theory_id: 3495
  - title: Access modifiers
    theory_id: 3589
  - title: Getters and setters
    theory_id: 3599
  - title: Static members
    theory_id: 3534
  - title: Annotations
    theory_id: 3622
  - title: Multiple constructors
    theory_id: 3538
  - title: Inheritance
    theory_id: 3583
  - title: The keyword super
    theory_id: 3588
  - title: Hiding and overriding
    theory_id: 3572
  - title: Build tools
    theory_id: 4284
  - title: Boxing and unboxing
    theory_id: 3595
  - title: Java Archive
    theory_id: 4311
  - title: Gradle basics
    theory_id: 5075
  - title: Basic project with Gradle
    theory_id: 5077
  - title: Building apps using Gradle
    theory_id: 7917
  - title: Dependency management
    theory_id: 5076
  1:
  - title: Hierarchy of exceptions
    theory_id: 3570
  - title: Exception handling
    theory_id: 3552
  - title: Generics and Object
    theory_id: 3493
  - title: The Collections Framework overview
    theory_id: 3624
  - title: Set
    theory_id: 3575
  - title: Passing JSON to server
    theory_id: 7165
  - title: Beans and components
    theory_id: 7353
  - title: 'Hashing: overview'
    theory_id: 9831
  - title: Hash table
    theory_id: 5364
  - title: Map
    theory_id: 3558
  - title: Protected modifier
    theory_id: 6692
  - title: Referencing subclass objects
    theory_id: 3585
  - title: Polymorphism
    theory_id: 3587
  - title: The Object class
    theory_id: 3596
  - title: Interface
    theory_id: 3615
  2:
  - title: Exception handling
    theory_id: 8780
  3:
  - title: Files
    theory_id: 6989
  - title: Data and object mapping
    theory_id: 8262
  - title: Introduction to databases
    theory_id: 8497
  - title: What is SQL
    theory_id: 7054
  - title: Object-Relational Mapping(ORM)
    theory_id: 8312
  - title: H2 database
    theory_id: 8762
  - title: Introduction to JPA
    theory_id: 8771
  - title: JPA Relationships
    theory_id: 8936
  5:
  - title: Default methods
    theory_id: 11354
  - title: Lambda expressions
    theory_id: 11635
  - title: Method references
    theory_id: 3620
  - title: Functional interfaces
    theory_id: 11636
  - title: Anonymous classes
    theory_id: 11896
