hyperskill_project:
  id: 130
  ide_files: https://stepik.org/media/attachments/lesson/405256/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Sun, 20 Jun 2021 11:22:18 UTC
stages:
- id: 692
  step: 11027
  is_completed: true
- id: 693
  step: 11028
  is_completed: true
- id: 694
  step: 11029
  is_completed: true
- id: 695
  step: 11030
  is_completed: true
- id: 696
  step: 11031
  is_completed: true
topics:
  0:
  - title: JVM, JRE, and JDK
    theory_id: 3499
  - title: Immutability
    theory_id: 7929
  - title: Units of information
    theory_id: 6865
  - title: IDE
    theory_id: 10996
  - title: Computer algorithms
    theory_id: 4953
  - title: The big O notation
    theory_id: 4991
  - title: Data structures
    theory_id: 5161
  - title: Fixed-size array
    theory_id: 7255
  - title: Dynamic array
    theory_id: 5357
  - title: World Wide Web
    theory_id: 6633
  - title: HyperText Transfer Protocol
    theory_id: 6569
  - title: HTTP URL
    theory_id: 6740
  - title: HTTP messages
    theory_id: 6752
  - title: REST
    theory_id: 7834
  - title: HTML basics
    theory_id: 6434
  - title: Tags and attributes
    theory_id: 7536
  - title: HTML page structure
    theory_id: 6491
  - title: Introduction to Spring boot
    theory_id: 7944
  - title: Postman
    theory_id: 8512
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Getting started with Spring Boot
    theory_id: 6336
  - title: Basic project structure
    theory_id: 6339
  - title: Introduction to Spring Web MVC
    theory_id: 13611
  - title: Getting data from REST
    theory_id: 13287
  - title: Posting and deleting data via REST
    theory_id: 13292
  - title: External resources
    theory_id: 6216
  - title: Computer programming
    theory_id: 8739
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  - title: Types and variables
    theory_id: 3518
  - title: Comments
    theory_id: 3520
  - title: Coding style conventions
    theory_id: 12411
  - title: Naming variables
    theory_id: 3513
  - title: Scanning the input
    theory_id: 9055
  - title: Introduction to OOP
    theory_id: 3614
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Increment and decrement
    theory_id: 5008
  - title: Characters
    theory_id: 3514
  - title: Conditional statement
    theory_id: 3503
  - title: Ternary operator
    theory_id: 3506
  - title: The for-loop
    theory_id: 3505
  - title: The while and do-while loops
    theory_id: 3498
  - title: Branching statements
    theory_id: 3507
  - title: Switch statement
    theory_id: 3504
  - title: Write, compile, and run
    theory_id: 3739
  - title: Errors in programs
    theory_id: 3536
  - title: What is an exception
    theory_id: 3497
  - title: NPE
    theory_id: 1945
  - title: Build tools
    theory_id: 4284
  - title: JSON
    theory_id: 6854
  - title: YAML
    theory_id: 12722
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Libraries
    theory_id: 8504
  - title: Frameworks
    theory_id: 6701
  - title: Calling a method
    theory_id: 10973
  - title: Declaring a method
    theory_id: 10982
  - title: The main method
    theory_id: 3489
  - title: Overloading
    theory_id: 3525
  - title: Functional decomposition
    theory_id: 10570
  - title: Primitive and reference types
    theory_id: 5035
  - title: Array
    theory_id: 3511
  - title: Iterating over arrays
    theory_id: 3602
  - title: Arrays as parameters
    theory_id: 3594
  - title: String
    theory_id: 3523
  - title: Final variables
    theory_id: 7427
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: IDEA Basics
    theory_id: 5819
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Java Archive
    theory_id: 4311
  - title: Gradle basics
    theory_id: 5075
  - title: Basic project with Gradle
    theory_id: 5077
  - title: Building apps using Gradle
    theory_id: 7917
  - title: Dependency management
    theory_id: 5076
  - title: Introduction to generic programming
    theory_id: 3492
  - title: Generics and Object
    theory_id: 3493
  - title: What are collections
    theory_id: 3770
  - title: The Collections Framework overview
    theory_id: 3624
  - title: ArrayList
    theory_id: 3567
  - title: The List interface
    theory_id: 3581
  - title: Defining classes
    theory_id: 3618
  - title: Constructor
    theory_id: 3535
  - title: Instance methods
    theory_id: 3495
  - title: Multiple constructors
    theory_id: 3538
  - title: Package
    theory_id: 3621
  - title: Access modifiers
    theory_id: 3589
  - title: Getters and setters
    theory_id: 3599
  - title: Inheritance
    theory_id: 3583
  - title: The keyword super
    theory_id: 3588
  - title: Protected modifier
    theory_id: 6692
  - title: Referencing subclass objects
    theory_id: 3585
  - title: The Object class
    theory_id: 3596
  - title: Annotations basics
    theory_id: 3622
  - title: Objects
    theory_id: 4727
  - title: Boxing and unboxing
    theory_id: 3595
  - title: Static members
    theory_id: 3534
  - title: Hiding and overriding
    theory_id: 3572
  - title: Polymorphism
    theory_id: 3587
  - title: Interface
    theory_id: 3615
  1:
  - title: Block-level elements
    theory_id: 7271
  - title: Inline Elements
    theory_id: 7518
  - title: Comments
    theory_id: 7502
  - title: What is CSS
    theory_id: 7678
  - title: Connecting CSS to HTML
    theory_id: 7418
  - title: Basic syntax
    theory_id: 7722
  - title: HTML attributes id and class
    theory_id: 7527
  - title: HTML forms
    theory_id: 6560
  - title: Comments
    theory_id: 7730
  - title: Border
    theory_id: 8355
  - title: Comments
    theory_id: 8170
  - title: Functions
    theory_id: 8388
  - title: Handling requests with bodies
    theory_id: 13334
  - title: Introduction to JavaScript
    theory_id: 8016
  - title: Overview of the basic program
    theory_id: 8154
  - title: Multi-line programs
    theory_id: 8162
  - title: Strings and numbers
    theory_id: 8194
  - title: Arithmetic operators
    theory_id: 8372
  - title: LocalDate
    theory_id: 3592
  - title: LocalTime
    theory_id: 3593
  - title: LocalDateTime
    theory_id: 3617
  2:
  - title: Absolute units
    theory_id: 10605
  - title: Relative units
    theory_id: 10671
  - title: Width and height
    theory_id: 8325
  - title: Margin and padding
    theory_id: 8346
  - title: Beans and components
    theory_id: 7353
  - title: Using FreeMarker with Spring Boot
    theory_id: 13634
  3:
  - title: Files
    theory_id: 13025
  - title: Introduction to databases
    theory_id: 8497
  - title: Relational Data Model
    theory_id: 13785
  - title: What is SQL
    theory_id: 7054
  - title: H2 database
    theory_id: 8762
  - title: Introduction to JPA
    theory_id: 8771
  - title: JPA relationships
    theory_id: 8936
  - title: CRUD repositories
    theory_id: 9536
  - title: Data and object mapping
    theory_id: 8262
  - title: Object-Relational Mapping (ORM)
    theory_id: 8312
  - title: Lambda expressions
    theory_id: 11635
  - title: Method references
    theory_id: 3620
  - title: Functional interfaces
    theory_id: 11636
  - title: Standard functional interfaces
    theory_id: 3623
  - title: Optional
    theory_id: 9699
  - title: Default methods
    theory_id: 11354
  - title: Anonymous classes
    theory_id: 11896
