<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <title>Create</title>
    <link rel="stylesheet"
          href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
    <link rel="stylesheet" href="css/styles.css">
    <script type="text/javascript" src="js/script.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
<code><textarea id="code_snippet">// write your code here</textarea></code>
<br/>
<input id="time_restriction" type="text"/>0</input>
<br/>
<input id="views_restriction" type="text"/>0</input>
<br/>
<button id="send_snippet" onclick="send()" type="submit">Submit</button>
</body>
</html>